# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wiki', '0002_auto_20160412_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='anchor',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
